// Fitness_App/src/Pages/Contact.jsx
import React from "react";
import "./Contact.css";

function Contact() {
  return (
    <div className="contact-container">
      <h2>Contact Us</h2>
      <p>If you have any questions or need support, feel free to reach out to us!</p>
      
      <div className="contact-details">
        <p><strong>Email:</strong> support@fitnessapp.com</p>
        <p><strong>Phone:</strong> +1 (555) 123-4567</p>
        <p><strong>Address:</strong> 123 Fitness St, Workout City, India</p>
      </div>

      <div className="contact-form">
        <h3>Send Us a Message</h3>
        <input type="text" placeholder="Your Name" />
        <input type="email" placeholder="Your Email" />
        <textarea placeholder="Your Message"></textarea>
        <button>Send Message</button>
      </div>
    </div>
  );
}

export default Contact;

// Angular_Assignment/ShopEase/src/app/pages/contact/contact.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.css'
})
export class ContactComponent {
  contact = {
    name: '',
    email: '',
    message: ''
  };

  submitForm() {
    console.log('Form submitted:', this.contact);
    alert('Your message has been sent successfully!');
  }

}

<div class="contact-container">
    <h2>Contact Us</h2>
  
    <form (submit)="submitForm()" class="contact-form">
      <div class="form-group">
        <label for="name">Name</label>
        <input type="text" id="name" [(ngModel)]="contact.name" name="name" required>
      </div>
  
      <div class="form-group">
        <label for="email">Email</label>
        <input type="email" id="email" [(ngModel)]="contact.email" name="email" required>
      </div>
  
      <div class="form-group">
        <label for="message">Message</label>
        <textarea id="message" [(ngModel)]="contact.message" name="message" rows="4" required></textarea>
      </div>
  
      <button type="submit" class="submit-btn">Send Message</button>
    </form>
  
    <div class="contact-info">
      <h3>Our Contact Details</h3>
      <p><strong>Email:</strong> support&#64;example.com</p>
      <p><strong>Phone:</strong> +1 234 567 890</p>
      <p><strong>Address:</strong> 123 Main Street, City, Country</p>
    </div>
  </div>
